### ISSUE TITLE
Code for RGB images 256* 256 image size

### ISSUE THREAD

**Issue by redhat12345** [mingyuliutw/CoGAN_PyTorch#3]
Can you tell me please how can I use your code for 256*256 color images ?

**Comment by mingyuliutw** [comment]
I don’t know if I will time to port more of the caffe code bass to this pytorch code. But if you are interested in high resolution image translation or domain adaptation, you could check out our NIPS 2017 paper. The code is available in my GitHub with the name, UNIT.
